### ISSUE TITLE
about id loss

### ISSUE THREAD

**Issue by q1vs5k5** [Hanson0910/RetinaTrack#4]

**Comment by q1vs5k5** [comment]
I'm curious about your IDloss  looks like different from the original paper which trained with triplet loss using the BatchHard strategy for sampling triplets.

**Comment by Hanson0910** [comment]
> I'm curious about your IDloss looks like different from the original paper which trained with triplet loss using the BatchHard strategy for sampling triplets.

i am sorry,it's just a quick implementation of the network structure,training strategy and loss i didn't refer the paper.

**Comment by q1vs5k5** [comment]
ok, thanks
